- sudo apt-get update && sudo apt-get install -y python3-pip
- pip3 install pipenv
- PATH=$PATH:/home/$USER/.local/bin
- pipenv --version
- pip3 install python-dotenv
- sudo mkdir -p /var/www/app
- sudo chown -R $USER:www-data /var/www/app
- sudo chmod -R 775 /var/www/app